Fix(Action): domain checking

diff --git a/.github/workflows/menual-test.yml b/.github/workflows/menual-test.yml
--- a/.github/workflows/menual-test.yml
+++ b/.github/workflows/menual-test.yml
@@ -57,7 +57,19 @@ jobs:
       - name: Build project
         run: npm run build
 
-      
+      - name: Check Domain Permissions
+        env:
+          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
+          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
+        run: |
+          # Check if the domain is owned by the organization
+          status=$(vercel domains list --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --json | jq -r '.[] | select(.name == "dev.qalbehabib.com") | .verification.status')
+          if [ "$status" = "VALID" ]; then
+            echo "Domain permissions are valid. Proceeding with alias assignment."
+          else
+            echo "Domain permissions are not valid. Unable to set alias."
+            exit 1
+          fi
 
       - name: Deploy to Vercel
         env:
@@ -69,7 +81,7 @@ jobs:
         run: |
           npm install -g vercel
           # Deploy to Vercel and capture the deployment URL
-          DEPLOYMENT_URL=$(vercel --prod --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --yes --env NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL --env NEXT_PUBLIC_HELIUS_URL=$NEXT_PUBLIC_HELIUS_URL | tee deployment.log | grep -o 'https:\/\/[a-zA-Z0-9.-]*\.vercel\.app')
+          DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --yes --env NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL --env NEXT_PUBLIC_HELIUS_URL=$NEXT_PUBLIC_HELIUS_URL | tee deployment.log | grep -o 'https:\/\/[a-zA-Z0-9.-]*\.vercel\.app')
           echo "Primary Deployment URL: $DEPLOYMENT_URL"
 
           # Attempt to assign the alias and capture any errors
